[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty --class scratchpad -e tmux new-session -c ~"
animation = "fromTop"
lazy = true

[scratchpads.discord]
command = "webcord"
position = "5% 5%"
class = "re:(WebCord|electron)"
lazy = true
